### PR TITLE
SA-3220: Remove Query Parameters for filter/fields

### PR DESCRIPTION
**Pull request by gweinjc**
## Issues
* [SA-3220](https://jumpcloud.atlassian.net/browse/SA-3220) - Remove Query Parameters for filter/fields

## What does this solve?
This removes the `filter1` and `fields1` parameters from the `Search-JcSdk*` functions

## Is there anything particularly tricky?
No

## How should this be tested?
Validate that the parameters `filter1` and `fields1` are not available for the following functions:
`Search-JcSdkCommand`
`Search-JcSdkOrganization`
`Search-JcSdkSystem`
`Search-JcSdkUser`

## Screenshots

[SA-3220]: https://jumpcloud.atlassian.net/browse/SA-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jworkmanjc — CHANGES_REQUESTED** [review]
The changelog files need to be updated but I was able to validate that each of the `search-jcsdk*` functions perform a filter using the body (as opposed to filter1 which was a query parameter in the request URL). Each of these functions no longer has a url query filter & fields parameter. As long as we update changelog files this PR is good to go!

**Review by kmaranionjc — CHANGES_REQUESTED** [review]
Changelog update needed otherwise it looks good.

**Review by jworkmanjc — APPROVED** [review]
Looks good to me!

**Review by kmaranionjc — APPROVED** [review]
Nice job!

**Pull request merged**
